version: "3"
services:
    privoxy:
      image: registry.cn-shanghai.aliyuncs.com/c-things/privoxy:v1
      restart: always
      container_name: privoxy
      ports:
       - 8181:8181
      volumes:
        - ./config:/etc/privoxy/config
